### ISSUE TITLE
Not working on current MoBIE

### ISSUE THREAD

**Issue by constantinpape** [mobie/plankton-fibsem-project#4]
Fails with the issue below; maybe the spec is not up-to-date or the data not on s3 yet.

```
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Module threw exception
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:307)
	at net.imagej.legacy.DefaultLegacyHooks.interceptRunPlugIn(DefaultLegacyHooks.java:166)
	at ij.IJ.runPlugIn(IJ.java)
	at ij.Executer.runCommand(Executer.java:150)
	at ij.Executer.run(Executer.java:68)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Module threw exception
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:303)
	... 5 more
Caused by: java.lang.RuntimeException: Module threw exception
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
Caused by: java.lang.NullPointerException
	at org.embl.mobie.viewer.bdv.view.ImageSliceView.adaptConverter(ImageSliceView.java:94)
	at org.embl.mobie.viewer.bdv.view.ImageSliceView.show(ImageSliceView.java:64)
	at org.embl.mobie.viewer.bdv.view.ImageSliceView.<init>(ImageSliceView.java:49)
	at org.embl.mobie.viewer.view.ViewManager.showImageDisplay(ViewManager.java:386)
	at org.embl.mobie.viewer.view.ViewManager.showSourceDisplay(ViewManager.java:353)
	at org.embl.mobie.viewer.view.ViewManager.show(ViewManager.java:305)
	at org.embl.mobie.viewer.MoBIE.openDataset(MoBIE.java:208)
	at org.embl.mobie.viewer.MoBIE.openDataset(MoBIE.java:142)
	at org.embl.mobie.viewer.MoBIE.<init>(MoBIE.java:78)
	at org.embl.mobie.viewer.command.OpenMoBIEProjectCommand.run(OpenMoBIEProjectCommand.java:25)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:163)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	... 6 more
```

**Comment by constantinpape** [comment]
The problem with the spec is fixed; but the data is not on s3 yet, see #2. I have requested a bucket now and will upload everything as soon as that's there.
